In [2]:
import pandas as pd
import sqlite3 as sql
#import numpy as np

In [4]:
dengbr21 = pd.read_csv('dengbr21.csv',delimiter=';')
dengbr22 = pd.read_csv('dengbr22.csv',delimiter=',')
dengbr19 = pd.read_csv('dengbr19.csv',delimiter=',')
dengbr18 = pd.read_csv('dengbr18.csv',delimiter=',')
dengbr17 = pd.read_csv('dengbr17.csv',delimiter=',')
dengbr16 = pd.read_csv('dengbr16.csv',delimiter=',')

C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_14504\3290894607.py:1: DtypeWarning: Columns (22,45,46,101) have mixed types. Specify dtype option on import or set low_memory=False.
  dengbr21 = pd.read_csv('dengbr21.csv',delimiter=';')
C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_14504\3290894607.py:2: DtypeWarning: Columns (44,46,54,101) have mixed types. Specify dtype option on import or set low_memory=False.
  dengbr22 = pd.read_csv('dengbr22.csv',delimiter=',')
C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_14504\3290894607.py:3: DtypeWarning: Columns (46,101) have mixed types. Specify dtype option on import or set low_memory=False.
  dengbr19 = pd.read_csv('dengbr19.csv',delimiter=',')
C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_14504\3290894607.py:4: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  dengbr18 = pd.read_csv('dengbr18.csv',delimiter=',')
C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_14504\3290894607.py:5: DtypeWarning: Columns (22,46,101) have mixed types. Specify dtype option on import or set low_memory=False.
  dengbr17 = pd.read_csv('dengbr17.csv',delimiter=',')
C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_14504\3290894607.py:6: DtypeWarning: Columns (22,44,45,46,85,101) have mixed types. Specify dtype option on import or set low_memory=False.
  dengbr16 = pd.read_csv('dengbr16.csv',delimiter=',')

In [5]:
unificada = [dengbr16,dengbr17,dengbr18,dengbr19,dengbr21,dengbr22]

for planilha in unificada:
    count_colunas = len(planilha.columns)
    print(count_colunas)

119
119
119
119
121
121

In [6]:
banco_dengue = pd.concat(unificada, ignore_index=True)
banco_dengue.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,DT_DIGITA,MIGRADO_W
0,2,A90,2016-12-08,201649,2016,12,120040,1938.0,7530684.0,2016-12-06,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,2,A90,2016-02-20,201607,2016,12,120040,1938.0,6439837.0,2016-02-19,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
2,2,A90,2016-02-14,201607,2016,12,120001,1938.0,5701929.0,2016-02-13,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3,2,A90,2016-02-18,201607,2016,12,120040,1938.0,6439837.0,2016-02-17,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
4,2,A90,2016-06-06,201623,2016,12,120020,1941.0,2002914.0,2016-06-02,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [7]:
banco_dengue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380516 entries, 0 to 380515
Columns: 122 entries, TP_NOT to MIGRADO_W
dtypes: float64(97), int64(5), object(20)
memory usage: 354.2+ MB

In [8]:
banco_dengue.describe()

,TP_NOT,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,SEM_PRI,NU_IDADE_N,CS_GESTANT,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,MIGRADO_W
count,380516.000000,380516.000000,380516.000000,380516.000000,380516.000000,246220.000000,3.805100e+05,380514.000000,380515.000000,380418.000000,...,2.000000,7.000000,1.0,2.0,292454.0,107.0,252341.000000,0.0,127290.000000,0.0
mean,2.000005,201894.500728,2018.742471,14.189795,142469.885258,2564.575993,3.763640e+06,201886.854817,3997.324805,5.722558,...,1.500000,156500.000000,1.0,8.0,2.0,1.0,0.604848,NaN,1990.383989,NaN
std,0.002293,217.850726,2.152421,2.215718,22767.581260,1651.875652,2.191455e+06,272.287594,226.726005,0.944554,...,0.707107,121933.383452,NaN,0.0,0.0,0.0,0.488884,NaN,18.919544,NaN
min,2.000000,201601.000000,2016.000000,11.000000,110001.000000,1342.000000,1.560000e+02,192839.000000,0.000000,1.000000,...,1.000000,22000.000000,1.0,8.0,2.0,1.0,0.000000,NaN,1905.000000,NaN
25%,2.000000,201706.000000,2017.000000,12.000000,120040.000000,1487.000000,2.319659e+06,201705.000000,4016.000000,5.000000,...,1.250000,49250.000000,1.0,8.0,2.0,1.0,0.000000,NaN,1978.000000,NaN
50%,2.000000,201905.000000,2019.000000,14.000000,140030.000000,1938.000000,2.667711e+06,201905.000000,4028.000000,6.000000,...,1.500000,165000.000000,1.0,8.0,2.0,1.0,1.000000,NaN,1992.000000,NaN
75%,2.000000,202113.000000,2021.000000,17.000000,170240.000000,1941.000000,5.376629e+06,202112.000000,4042.000000,6.000000,...,1.750000,247500.000000,1.0,8.0,2.0,1.0,1.000000,NaN,2005.000000,NaN
max,3.000000,202252.000000,2022.000000,17.000000,412680.000000,5590.000000,9.985220e+06,202252.000000,4406.000000,9.000000,...,2.000000,315000.000000,1.0,8.0,2.0,1.0,1.000000,NaN,2022.000000,NaN

In [9]:
banco_dengue.isnull().sum()

TP_NOT             0
ID_AGRAVO          0
DT_NOTIFIC         0
SEM_NOT            0
NU_ANO             0
               ...
CS_FLXRET     128175
FLXRECEBI     380516
ANO_NASC      253226
DT_DIGITA     253757
MIGRADO_W     380516
Length: 122, dtype: int64

In [10]:
banco_dengue = banco_dengue.fillna('Não Informado')
banco_dengue.isnull().sum()

TP_NOT        0
ID_AGRAVO     0
DT_NOTIFIC    0
SEM_NOT       0
NU_ANO        0
             ..
CS_FLXRET     0
FLXRECEBI     0
ANO_NASC      0
DT_DIGITA     0
MIGRADO_W     0
Length: 122, dtype: int64

In [11]:
colunas = banco_dengue.columns
colunas_dt = [col for col in colunas if "DT_" in col] #List comprehension
colunas_dt

['DT_NOTIFIC',
 'DT_SIN_PRI',
 'DT_NASC',
 'DT_INVEST',
 'DT_CHIK_S1',
 'DT_CHIK_S2',
 'DT_PRNT',
 'DT_SORO',
 'DT_NS1',
 'DT_VIRAL',
 'DT_PCR',
 'DT_INTERNA',
 'DT_OBITO',
 'DT_ENCERRA',
 'DT_ALRM',
 'DT_GRAV',
 'DT_DIGITA']

In [15]:
for coluna in colunas_dt:
    banco_dengue[coluna] = pd.to_datetime(banco_dengue[coluna], errors='coerce')
    print(banco_dengue[coluna].count())

380516
380510
250935
360721
1294
5
172
116731
44316
1530
10900
17939
519
378225
2463
220
126759

In [21]:
colunas = banco_dengue.columns

for coluna in colunas:
    tipo_coluna = banco_dengue[coluna].dtype
    print(f'{coluna}: {tipo_coluna}')

TP_NOT: int64
ID_AGRAVO: object
DT_NOTIFIC: datetime64[ns]
SEM_NOT: int64
NU_ANO: int64
SG_UF_NOT: int64
ID_MUNICIP: int64
ID_REGIONA: object
ID_UNIDADE: object
DT_SIN_PRI: datetime64[ns]
SEM_PRI: object
DT_NASC: datetime64[ns]
NU_IDADE_N: object
CS_SEXO: object
CS_GESTANT: object
CS_RACA: object
CS_ESCOL_N: object
SG_UF: object
ID_MN_RESI: object
ID_RG_RESI: object
ID_PAIS: object
DT_INVEST: datetime64[ns]
ID_OCUPA_N: object
FEBRE: object
MIALGIA: object
CEFALEIA: object
EXANTEMA: object
VOMITO: object
NAUSEA: object
DOR_COSTAS: object
CONJUNTVIT: object
ARTRITE: object
ARTRALGIA: object
PETEQUIA_N: object
LEUCOPENIA: object
LACO: object
DOR_RETRO: object
DIABETES: object
HEMATOLOG: object
HEPATOPAT: object
RENAL: object
HIPERTENSA: object
ACIDO_PEPT: object
AUTO_IMUNE: object
DT_CHIK_S1: datetime64[ns]
DT_CHIK_S2: datetime64[ns]
DT_PRNT: datetime64[ns]
RES_CHIKS1: object
RES_CHIKS2: object
RESUL_PRNT: object
DT_SORO: datetime64[ns]
RESUL_SORO: object
DT_NS1: datetime64[ns]
RESUL_NS1: object
DT_VIRAL: datetime64[ns]
RESUL_VI_N: object
DT_PCR: datetime64[ns]
RESUL_PCR_: object
SOROTIPO: object
HISTOPA_N: object
IMUNOH_N: object
HOSPITALIZ: object
DT_INTERNA: datetime64[ns]
UF: object
MUNICIPIO: object
TPAUTOCTO: object
COUFINF: object
COPAISINF: object
COMUNINF: object
CLASSI_FIN: object
CRITERIO: object
DOENCA_TRA: object
CLINC_CHIK: object
EVOLUCAO: object
DT_OBITO: datetime64[ns]
DT_ENCERRA: datetime64[ns]
ALRM_HIPOT: object
ALRM_PLAQ: object
ALRM_VOM: object
ALRM_SANG: object
ALRM_HEMAT: object
ALRM_ABDOM: object
ALRM_LETAR: object
ALRM_HEPAT: object
ALRM_LIQ: object
DT_ALRM: datetime64[ns]
GRAV_PULSO: object
GRAV_CONV: object
GRAV_ENCH: object
GRAV_INSUF: object
GRAV_TAQUI: object
GRAV_EXTRE: object
GRAV_HIPOT: object
GRAV_HEMAT: object
GRAV_MELEN: object
GRAV_METRO: object
GRAV_SANG: object
GRAV_AST: object
GRAV_MIOC: object
GRAV_CONSC: object
GRAV_ORGAO: object
DT_GRAV: datetime64[ns]
MANI_HEMOR: object
EPISTAXE: object
GENGIVO: object
METRO: object
PETEQUIAS: object
HEMATURA: object
SANGRAM: object
LACO_N: object
PLASMATICO: object
EVIDENCIA: object
PLAQ_MENOR: object
CON_FHD: object
COMPLICA: object
TP_SISTEMA: object
NDUPLIC_N: object
CS_FLXRET: object
FLXRECEBI: object
ANO_NASC: object
DT_DIGITA: datetime64[ns]
MIGRADO_W: object
diferenca_dias: float64

In [16]:
# Calcular a diferença entre as dias das datas de notificação e as datas dos sintomas
banco_dengue['diferenca_dias'] = (banco_dengue['DT_NOTIFIC'] - banco_dengue['DT_SIN_PRI']).dt.days

# Ordenar o DataFrame pela coluna 'diferenca_dias' em ordem decrescente
dengue_ordenado = banco_dengue.sort_values(by='diferenca_dias', ascending=False)
resultado_dias = dengue_ordenado[['DT_NOTIFIC', 'DT_SIN_PRI', 'diferenca_dias']]
resultado_dias.head(30)

       DT_NOTIFIC DT_SIN_PRI  diferenca_dias
212315 2019-02-13 1928-09-27         33011.0
185685 2019-11-14 1934-06-28         31185.0
213894 2019-03-29 1935-01-21         30748.0
9089   2016-01-22 1931-11-20         30744.0
193072 2019-11-20 1939-01-10         29534.0
80507  2016-05-02 1937-09-03         28731.0
181239 2019-12-07 1942-11-27         28134.0
204102 2019-07-01 1944-03-26         27490.0
167885 2018-04-17 1944-01-27         27109.0
118410 2017-02-06 1943-05-25         26921.0
58802  2016-03-12 1942-10-24         26803.0
3114   2016-08-24 1945-08-23         25934.0
31057  2016-05-03 1946-06-30         25510.0
127505 2017-09-18 1947-12-13         25482.0
174801 2018-12-05 1949-06-25         25365.0
43339  2016-08-22 1947-04-17         25330.0
122209 2017-06-28 1948-04-30         25261.0
152147 2018-12-18 1949-12-13         25207.0
55894  2016-04-19 1948-03-08         24879.0
6843   2016-07-15 1949-05-09         24539.0
38534  2016-02-04 1949-04-13         24403.0
194789 2019-04-12 1952-07-24         24368.0
81457  2016-03-10 1950-05-22         24034.0
212960 2019-02-06 1953-06-12         23980.0
137720 2017-03-29 1952-04-22         23717.0
200726 2019-09-13 1954-10-27         23697.0
77846  2016-12-27 1952-02-26         23681.0
138625 2017-01-28 1952-06-02         23616.0
190437 2019-01-10 1955-04-29         23267.0
73643  2016-01-16 1952-05-15         23256.0

In [17]:
banco_dengue.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,CS_FLXRET,FLXRECEBI,ANO_NASC,DT_DIGITA,MIGRADO_W,diferenca_dias
0,2,A90,2016-12-08,201649,2016,12,120040,1938.0,7530684.0,2016-12-06,...,Não Informado,Não Informado,Não Informado,Não Informado,1.0,Não Informado,Não Informado,NaT,Não Informado,2.0
1,2,A90,2016-02-20,201607,2016,12,120040,1938.0,6439837.0,2016-02-19,...,Não Informado,Não Informado,Não Informado,Não Informado,1.0,Não Informado,Não Informado,NaT,Não Informado,1.0
2,2,A90,2016-02-14,201607,2016,12,120001,1938.0,5701929.0,2016-02-13,...,Não Informado,Não Informado,Não Informado,Não Informado,1.0,Não Informado,Não Informado,NaT,Não Informado,1.0
3,2,A90,2016-02-18,201607,2016,12,120040,1938.0,6439837.0,2016-02-17,...,Não Informado,Não Informado,Não Informado,Não Informado,1.0,Não Informado,Não Informado,NaT,Não Informado,1.0
4,2,A90,2016-06-06,201623,2016,12,120020,1941.0,2002914.0,2016-06-02,...,Não Informado,Não Informado,Não Informado,Não Informado,1.0,Não Informado,Não Informado,NaT,Não Informado,4.0

In [14]:
#banco_dengue.to_csv('banco_dengue_unificado.csv',index=False)